site_name: SKA Docs (Draft)
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

plugins:
  - social

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Scotland-Korfball
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ScotlandKorf

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2023-<script>document.write(new Date().getFullYear())</script> <a href="https://scotlandkorfball.co.uk/"  target="_blank" rel="noopener">Scottish Korfball Association</a>.