name: Build/Publish Latest Release Docs
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install Dependencies
        run: |
          pip install mkdocs-material
          pip install pillow cairosvg mike
      - name: Setup Docs Deploy
        run: |
          git config --global user.name "Docs Deploy"
          git config --global user.email "safeguarding@scotlandkorfball.co.uk"
      - name: Mike Set Default
        run: mike set-default latest --allow-undefined
      - name: Build Docs Website
        run: mike deploy --push --update-aliases ${{ github.event.release.tag_name }} latest